# Generated by Django 3.2.10 on 2022-03-21 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import inventory.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(default='Not Set', max_length=150)),
                ('categorynotes', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('manufactureid', models.AutoField(primary_key=True, serialize=False)),
                ('manufacture', models.CharField(default='Not Set', max_length=150)),
                ('manufacturenotes', models.CharField(blank=True, max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('serialnumber', models.IntegerField(blank=True, null=True)),
                ('item', models.CharField(default='Not Set', max_length=150)),
                ('quantity', models.IntegerField()),
                ('quantitydate', models.DateField(default=django.utils.timezone.now)),
                ('price', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('category', models.ForeignKey(default='Unspecified', on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.manufacture')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiondate', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('hh', models.IntegerField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, max_length=150, null=True)),
                ('checkoutdate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('checkindate', models.DateField(blank=True, default=inventory.models.add_time, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('itemid', models.ForeignKey(default=119, on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
        ),
    ]
