# Generated by Django 4.0 on 2021-12-26 02:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('manufacture', models.CharField(default='Not Set', max_length=150)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('serialnumber', models.IntegerField(blank=True, null=True)),
                ('item', models.CharField(default='Not Set', max_length=150)),
                ('price', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiondate', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('hh', models.IntegerField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, max_length=150, null=True)),
                ('checkoutdate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('checkindate', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('itemid', models.ForeignKey(default=119, on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
        ),
    ]
