# Generated by Django 4.0 on 2021-12-24 04:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacture', models.CharField(default='Not Set', max_length=150)),
                ('category', models.CharField(blank=True, max_length=150, null=True)),
                ('serialnumber', models.IntegerField(blank=True, null=True)),
                ('item', models.CharField(default='Not Set', max_length=150)),
                ('price', models.FloatField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactiondate', models.DateField(default=datetime.datetime(2021, 12, 24, 4, 3, 14, 880814))),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('hh', models.IntegerField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, max_length=150, null=True)),
                ('checkoutdate', models.DateField(default=datetime.datetime(2021, 12, 24, 4, 3, 14, 880938))),
                ('checkindate', models.DateField(default=datetime.datetime(2021, 12, 24, 4, 3, 14, 880955))),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('item', models.ForeignKey(default='Not Set', on_delete=django.db.models.deletion.CASCADE, to='inventory.products')),
            ],
        ),
    ]
