# Generated by Django 4.0 on 2021-12-27 01:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantitydate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
